### ISSUE TITLE
Cannot inject providers by name

### ISSUE THREAD

**Issue by mebibou** [vsternbach/angularjs-testbed#2]
This does not seem to work:
```
interface IFooResource extends ng.resource.IResourceClass<IFoo> {}

function FooResource($resource: ng.resource.IResourceService) {
  return $resource('/foo/:id', {
    format: 'json',
    id: '@id'
  });
}

describe('FooResource', () => {
  let resource: IFooResource;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        ngResource
      ],
      providers: [{
        provide: 'FooResource',
        useFactory: ($resource) => FooResource($resource),
        deps: [
          '$resource'
        ]
      }]
    })
    .compileComponents();

    resource = TestBed.get('FooResource');
  });
});
```
it gives a `Error: [$injector:unpr] Unknown provider: FooResourceProvider <- FooResource` error. 

Maybe there is another way to import the resource?

**Comment by vsternbach** [comment]
One of the things that could cause this behavior in a test suite could be missing `TestBed.resetTestingModule()`, you should add it in after each:
```
afterEach(() => TestBed.resetTestingModule());
```
Couldn't find it right now, but I think I saw in angular testing documentation that they doing the same thing, only they patched jasmine to reset TestingModule on each test.
If you're running your tests from the single file (like in angular), you can put it there.
I know this library lacks a proper documentation, I am working on adding some example project using angular-ts-decoratos and angularjs-testbed and will upload it soon

**Comment by vsternbach** [comment]
Besides, I doubt this is the right way to test, you should be providing stub for $resource anyway, you don't want to test the $resource itself

**Comment by mebibou** [comment]
yes the `afterEach` did the trick, thanks!  I have a file that is loaded before the tests and I just added there
